# Generated by Django 4.2.8 on 2024-02-07 03:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_homepagegalleryimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomePageGalleryImage",
        ),
    ]
