# Generated by Django 4.2.8 on 2024-02-07 03:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_homepagegalleryimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepagegalleryimage",
            name="title",
        ),
    ]
