# Generated by Django 4.2.8 on 2024-02-09 06:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0005_founderpagegalleryimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FounderPageGalleryImage",
        ),
    ]
