# Generated by Django 4.2.8 on 2024-02-20 21:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0013_boxchat"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BoxChat",
        ),
    ]
