# Generated by Django 4.2.8 on 2024-02-20 21:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0015_chatwidget"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatWidget",
        ),
    ]
