# Generated by Django 4.2.8 on 2024-02-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0016_delete_chatwidget"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZaloChatWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_code", models.TextField()),
            ],
        ),
    ]
