# Generated by Django 4.2.8 on 2024-02-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("new", "0002_newindexpage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="newindexpage",
            name="title2",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
