# Generated by Django 4.2.8 on 2024-03-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_customerinquiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("number_phone", models.CharField(max_length=15)),
                ("support", models.CharField(max_length=100)),
                ("message", models.TextField()),
            ],
        ),
    ]
