# Generated by Django 4.2.8 on 2024-02-09 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_blogindexthreepage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogIndexThreePage",
        ),
    ]
